inherit_from:
  - https://style.domainic.org/rubocop/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Naming/FileName:
  Exclude:
    - lib/domainic-attributer.rb
    - sig/domainic-attributer.rbs